# Generated by Django 6.0.6 on 2026-06-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='profile_image_public_id',
            field=models.CharField(blank=True, help_text='Cloudinary public ID for managing the image', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='profile_image_url',
            field=models.URLField(blank=True, help_text='Public URL of the profile image from Cloudinary', max_length=500, null=True),
        ),
    ]
