# Generated by Django 6.0.6 on 2026-08-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_accounts_profile_image_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='account_status',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', help_text="Whether the user's account is public or private", max_length=10),
        ),
    ]
