# Generated by Django 6.0.6 on 2026-09-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_accounts_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='paystack_recipient_code',
            field=models.CharField(blank=True, help_text='Paystack recipient code for M-Pesa withdrawals (stored after first withdrawal)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='paystack_recipient_created_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when Paystack recipient was created', null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='paystack_recipient_phone',
            field=models.CharField(blank=True, help_text='Formatted phone number used for Paystack recipient', max_length=15, null=True),
        ),
    ]
