# Generated by Django 6.0.6 on 2026-09-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_accounts_paystack_recipient_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='account_status',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='paystack_recipient_code',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='paystack_recipient_created_at',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='paystack_recipient_phone',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='profile_image_public_id',
        ),
        migrations.AddField(
            model_name='accounts',
            name='auth_provider',
            field=models.CharField(choices=[('local', 'Local'), ('google', 'Google')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='accounts',
            name='google_id',
            field=models.CharField(blank=True, help_text='Unique Google account ID.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='profile_image_url',
            field=models.URLField(blank=True, help_text='Optional profile image URL.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('serviceprovider', 'Service Provider'), ('serviceseeker', 'Service Seeker')], default='serviceseeker', max_length=20),
        ),
    ]
