# Generated by Django 6.0.6 on 2026-09-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_accounts_account_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='profile_image_public_id',
            field=models.CharField(blank=True, help_text='Cloudinary public ID for the profile image.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='profile_image_url',
            field=models.URLField(blank=True, help_text='Cloudinary profile image URL.', max_length=1000, null=True),
        ),
    ]
