# Generated by Django 6.0.6 on 2026-09-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_accounts_profile_image_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Premium/Verified status. Only applicable to service providers.'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='premium_expires_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when Premium/Verified status expires. Only applicable to service providers.', null=True),
        ),
    ]
