# Generated by Django 6.0.6 on 2026-09-26 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_accounts_is_premium_accounts_premium_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='premium_expires_at',
        ),
    ]
