# Generated by Django 6.0.6 on 2026-10-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_accounts_is_premium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
