# Generated by Django 6.0.6 on 2026-10-10 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_accounts_role'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='The plan this account is currently on.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='plans.plan'),
        ),
    ]
