# Generated by Django 6.0.6 on 2026-10-10 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_accounts_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='plan',
        ),
    ]
