# Generated by Django 6.0.6 on 2026-10-03 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Businesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('business_category', models.CharField(choices=[('goods', 'Goods'), ('services', 'Services')], max_length=20)),
                ('business_type', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('county', models.CharField(max_length=120)),
                ('city_town', models.CharField(help_text='City or town where the business is located.', max_length=120)),
                ('region', models.CharField(choices=[('village', 'Village'), ('closest', 'Closest')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='The account that owns this business.', on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['owner'], name='businesses__owner_i_d815c9_idx'), models.Index(fields=['business_category'], name='businesses__busines_b90a45_idx'), models.Index(fields=['county', 'city_town'], name='businesses__county_d79b9f_idx')],
            },
        ),
    ]
