# Generated by Django 6.0.6 on 2026-10-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesses',
            name='region',
            field=models.CharField(blank=True, help_text='Specific area or locality, e.g. Kasuku, Kawangware.', max_length=120, null=True),
        ),
    ]
