# Generated by Django 6.0.6 on 2026-10-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_alter_businesses_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesses',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='businesses',
            name='region',
            field=models.CharField(help_text='Specific area or locality, e.g. Kasuku, Kawangware.', max_length=120),
        ),
    ]
