# Generated by Django 6.0.6 on 2026-10-03 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_businesses_description_alter_businesses_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businesses',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('draft', 'Draft'), ('closed', 'Closed'), ('suspended', 'Suspended')], default='active', help_text='Current lifecycle state of the business.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='businesses',
            index=models.Index(fields=['status'], name='businesses__status_19b18d_idx'),
        ),
    ]
