# Generated by Django 6.0.2 on 2026-03-13 20:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_alter_clientprofile_created_by_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(help_text="Client's age (must be 18 or older)", validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(120)])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('nonbinary', 'Non-binary'), ('prefer_not_say', 'Prefer not to say')], help_text="Client's gender", max_length=20)),
                ('country', models.CharField(default='Kenya', help_text='Country of residence', max_length=100)),
                ('county', models.CharField(help_text='County of residence', max_length=100)),
                ('location_desc', models.TextField(help_text='Detailed location description (area, landmark, etc.)', max_length=500)),
                ('uploaded_img', models.URLField(blank=True, help_text='Cloudinary URL of the uploaded image', max_length=500, null=True)),
                ('uploaded_img_public_id', models.CharField(blank=True, help_text='Cloudinary public ID for the uploaded image (used for deletions)', max_length=255, null=True)),
                ('info', models.TextField(help_text="Client's bio, what they're looking for, etc.", max_length=1000)),
                ('phone_number', models.CharField(blank=True, help_text='Optional phone number', max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text='Optional date of birth', null=True)),
                ('occupation', models.CharField(blank=True, help_text='Optional occupation', max_length=200, null=True)),
                ('interests', models.TextField(blank=True, help_text='Optional interests/hobbies', max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this bio is active')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the client has been verified')),
                ('verification_document', models.URLField(blank=True, help_text='Optional verification document URL', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_profile', models.OneToOneField(help_text='The client this bio belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='bio', to='accounts.clientprofile')),
            ],
            options={
                'verbose_name': 'Client Bio',
                'verbose_name_plural': 'Client Bios',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['country', 'county'], name='clientbio_b_country_f39c59_idx'), models.Index(fields=['is_active', 'is_verified'], name='clientbio_b_is_acti_eb6df4_idx'), models.Index(fields=['created_at'], name='clientbio_b_created_eda9a0_idx')],
            },
        ),
    ]
