# Generated by Django 6.0.6 on 2026-09-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Human-readable category name, e.g. 'Teaching'.", max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-safe identifier auto-generated from name.', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Short description shown to providers when picking a category.')),
                ('image_url', models.URLField(blank=True, help_text='Optional image/illustration for the category.', max_length=500, null=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first. Ties broken alphabetically.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive categories are hidden from the public API.')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Featured categories can be pinned to the top of the UI.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='services_se_is_acti_fb7379_idx'), models.Index(fields=['is_featured', 'display_order'], name='services_se_is_feat_f18028_idx')],
            },
        ),
    ]
