# Generated by Django 6.0.6 on 2026-09-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['name'], 'verbose_name': 'Service Category', 'verbose_name_plural': 'Service Categories'},
        ),
        migrations.RemoveIndex(
            model_name='servicecategory',
            name='services_se_is_acti_fb7379_idx',
        ),
        migrations.RemoveIndex(
            model_name='servicecategory',
            name='services_se_is_feat_f18028_idx',
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['is_active', 'name'], name='services_se_is_acti_79641e_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['is_featured', 'name'], name='services_se_is_feat_7899a1_idx'),
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='image_url',
        ),
    ]
