# Generated by Django 6.0.6 on 2026-09-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_servicecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional image/illustration for the category.', max_length=500, null=True),
        ),
    ]
