# Generated by Django 6.0.6 on 2026-09-17 17:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicecategory_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.CreateModel(
            name='ClientService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(choices=[('service', 'Service'), ('product', 'Product')], db_index=True, default='service', help_text='Whether this listing represents a service or a product/good for sale.', max_length=20)),
                ('title', models.CharField(db_index=True, help_text="Name of the service or product, e.g. 'Mathematics Tutoring' or 'Toyota Premio 2018'.", max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the service or product.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in Kenyan Shillings (KES).', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('pricing_unit', models.CharField(choices=[('per_hour', 'Per Hour'), ('per_day', 'Per Day'), ('per_week', 'Per Week'), ('per_month', 'Per Month'), ('per_job', 'Per Job'), ('per_item', 'Per Item')], default='per_job', help_text='How the listed price is charged.', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive listings are hidden from public results.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='The single category this service/product belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='client_services', to='services.servicecategory')),
                ('provider', models.ForeignKey(help_text='User providing or selling this service/product.', limit_choices_to={'role__in': ['serviceprovider', 'superadmin']}, on_delete=django.db.models.deletion.CASCADE, related_name='client_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Service',
                'verbose_name_plural': 'Client Services',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'is_active'], name='services_cl_provide_cb1042_idx'), models.Index(fields=['category', 'is_active'], name='services_cl_categor_fb21c4_idx'), models.Index(fields=['listing_type', 'is_active'], name='services_cl_listing_a81700_idx'), models.Index(fields=['title'], name='services_cl_title_7b9cd3_idx')],
            },
        ),
    ]
