# Generated by Django 6.0.6 on 2026-09-17 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_servicecategory_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='Cloudinary secure URL for this image (https://res.cloudinary.com/...).', max_length=1000)),
                ('image_public_id', models.CharField(blank=True, default='', help_text='Cloudinary public ID, used for deleting or replacing the asset.', max_length=500)),
                ('is_primary', models.BooleanField(db_index=True, default=False, help_text='Whether this image is the cover for the listing. Only one image per service should be primary.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(help_text='The service/product this image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.clientservice')),
            ],
            options={
                'verbose_name': 'Service Image',
                'verbose_name_plural': 'Service Images',
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['service', 'display_order'], name='services_se_service_59ded0_idx'), models.Index(fields=['service', 'is_primary'], name='services_se_service_e2776e_idx')],
            },
        ),
    ]
