# Generated by Django 6.0.6 on 2026-09-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_serviceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservice',
            name='listing_type',
            field=models.CharField(choices=[('service', 'Service'), ('product', 'Product'), ('hookup', 'Hookup')], db_index=True, default='service', help_text='Whether this listing is a service, a product for sale, or a hookup / companionship offer.', max_length=20),
        ),
    ]
