# Generated by Django 6.0.6 on 2026-09-17 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_clientservice_listing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservice',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Detailed description of the service or product. Optional for hookup listings.'),
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in Kenyan Shillings (KES). Optional for hookup listings.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='pricing_unit',
            field=models.CharField(blank=True, choices=[('per_hour', 'Per Hour'), ('per_day', 'Per Day'), ('per_week', 'Per Week'), ('per_month', 'Per Month'), ('per_job', 'Per Job'), ('per_item', 'Per Item')], default='per_job', help_text='How the listed price is charged.', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='title',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Name of the service or product, e.g. 'Mathematics Tutoring' or 'Toyota Premio 2018'. Optional for hookup listings.", max_length=255),
        ),
    ]
