# Generated by Django 6.0.6 on 2026-09-18 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_clientservice_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientservice',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Featured listings are highlighted in the feed and search results.'),
        ),
        migrations.AddIndex(
            model_name='clientservice',
            index=models.Index(fields=['is_featured', 'is_active'], name='services_cl_is_feat_ed0329_idx'),
        ),
    ]
