# Generated by Django 6.0.6 on 2026-10-10 15:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('payment', 'Payment'), ('subscription', 'Subscription'), ('system', 'System'), ('security', 'Security'), ('social', 'Social'), ('business', 'Business'), ('engagement', 'Engagement'), ('promo', 'Promotion')], db_index=True, default='system', max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, default='info', max_length=10)),
                ('title', models.CharField(help_text='Short headline, shown first.', max_length=200)),
                ('body', models.TextField(blank=True, default='', help_text='Longer descriptive text.')),
                ('action_label', models.CharField(blank=True, default='', help_text="Text for the action button, e.g. 'View invoice'.", max_length=80)),
                ('action_url', models.CharField(blank=True, default='', help_text="Frontend route the action button links to, e.g. '/useraccount/billing'.", max_length=500)),
                ('metadata', models.JSONField(blank=True, help_text='Optional JSON payload for the frontend.', null=True)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, help_text='When the recipient opened this notification.', null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Optional expiry. Null = never expires.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, help_text='The user who triggered this notification, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(help_text='The account this notification is delivered to.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at'], name='notificatio_recipie_ce9d56_idx'), models.Index(fields=['recipient', 'category', '-created_at'], name='notificatio_recipie_7b1202_idx'), models.Index(fields=['recipient', 'severity', '-created_at'], name='notificatio_recipie_6e0468_idx'), models.Index(fields=['expires_at'], name='notificatio_expires_4f3289_idx')],
            },
        ),
    ]
