# Generated by Django 6.0.6 on 2026-07-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('connection_request', 'Connection Request'), ('connection_accepted', 'Connection Accepted'), ('connection_rejected', 'Connection Rejected'), ('connection_completed', 'Connection Completed'), ('payment_pending', 'Payment Pending'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed')], max_length=50),
        ),
    ]
