# Generated by Django 6.0.6 on 2026-09-26 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_alter_connection_unique_together_and_more'),
        ('services', '0008_clientservice_is_featured_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='service',
            field=models.ForeignKey(blank=True, help_text='The service listing this connection relates to, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connections', to='services.clientservice'),
        ),
        migrations.AddField(
            model_name='connection',
            name='source',
            field=models.CharField(choices=[('hookup', 'Hookup'), ('service', 'Service Contact'), ('advert', 'Advert')], default='hookup', help_text='How this connection was created.', max_length=20),
        ),
        migrations.AlterField(
            model_name='connection',
            name='receiver',
            field=models.ForeignKey(help_text='The user whose contact the initiator wants to unlock.', on_delete=django.db.models.deletion.CASCADE, related_name='received_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='connection',
            name='sender',
            field=models.ForeignKey(help_text='The user who initiated the connection.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_connections', to=settings.AUTH_USER_MODEL),
        ),
    ]
