# Generated by Django 6.0.6 on 2026-09-26 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_connection_service_connection_source_and_more'),
        ('services', '0008_clientservice_is_featured_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='connection',
            name='unique_active_connection',
        ),
        migrations.AlterField(
            model_name='connection',
            name='source',
            field=models.CharField(choices=[('hookup', 'Hookup'), ('service', 'Service Contact'), ('advert', 'Advert')], db_index=True, default='hookup', help_text='How this connection was created.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['sender', 'receiver'], name='connections_sender__6e3715_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['source'], name='connections_source_0e8a11_idx'),
        ),
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'hookup')), fields=('sender', 'receiver'), name='unique_hookup_connection'),
        ),
        migrations.RemoveField(
            model_name='connection',
            name='status',
        ),
    ]
