# Generated by Django 6.0.6 on 2026-09-26 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_remove_connection_unique_active_connection_and_more'),
        ('payments', '0004_remove_payment_payment_type_payment_category_and_more'),
        ('services', '0008_clientservice_is_featured_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='connection',
            name='unique_hookup_connection',
        ),
        migrations.AddField(
            model_name='connection',
            name='payment',
            field=models.OneToOneField(blank=True, help_text='The payment that activates this connection. Status is read from here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_connection', to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='receiver',
            field=models.ForeignKey(help_text='The user whose contact is being unlocked.', on_delete=django.db.models.deletion.CASCADE, related_name='received_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='connection',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connections', to='services.clientservice'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='source',
            field=models.CharField(choices=[('hookup', 'Hookup'), ('service', 'Service Contact'), ('advert', 'Advert')], db_index=True, default='hookup', max_length=20),
        ),
    ]
