# Generated by Django 6.0.2 on 2026-03-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hookup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hookup',
            name='amount',
        ),
    ]
