# Generated by Django 6.0.2 on 2026-04-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_clientprofile_created_by_admin_and_more'),
        ('hookup', '0004_hookup_deleted_at_hookup_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hookup',
            name='unique_pending_hookup',
        ),
        migrations.RenameField(
            model_name='hookup',
            old_name='cancelled_at',
            new_name='approved_at',
        ),
        migrations.RenameField(
            model_name='hookup',
            old_name='is_deleted',
            new_name='is_deleted_by_receiver',
        ),
        migrations.RenameField(
            model_name='hookup',
            old_name='completed_at',
            new_name='rejected_at',
        ),
        migrations.AddField(
            model_name='hookup',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='hookup',
            name='is_deleted_by_sender',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hookup',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('not_paid', 'Not Paid')], default='not_paid', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='hookup',
            constraint=models.UniqueConstraint(condition=models.Q(('approval_status', 'pending')), fields=('sender', 'receiver'), name='unique_pending_hookup'),
        ),
        migrations.RemoveField(
            model_name='hookup',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='hookup',
            name='responded_at',
        ),
        migrations.RemoveField(
            model_name='hookup',
            name='scheduled_deletion_at',
        ),
        migrations.RemoveField(
            model_name='hookup',
            name='status',
        ),
    ]
