# Generated by Django 6.0.2 on 2026-04-12 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_alter_clientprofile_created_by_admin_and_more'),
        ('hookup', '0005_remove_hookup_unique_pending_hookup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('pesapal', 'Pesapal')], default='pesapal', max_length=20)),
                ('merchant_reference', models.CharField(max_length=100, unique=True)),
                ('order_tracking_id', models.CharField(blank=True, max_length=100, null=True)),
                ('redirect_url', models.URLField(blank=True, max_length=500, null=True)),
                ('callback_url', models.URLField(blank=True, max_length=500, null=True)),
                ('ipn_id', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('pesapal_response', models.JSONField(blank=True, null=True)),
                ('pesapal_status_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.clientprofile')),
                ('hookup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='hookup.hookup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
