# Generated by Django 6.0.6 on 2026-08-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('pesapal', 'PesaPal'), ('paystack', 'Paystack')], default='pesapal', help_text='Payment gateway used (PesaPal or Paystack)', max_length=20),
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payments',
        ),
    ]
