# Generated by Django 6.0.2 on 2026-04-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='callback_url',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='redirect_url',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
