# Generated by Django 6.0.6 on 2026-09-24 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_alter_connection_unique_together_and_more'),
        ('payments', '0002_alter_payment_options_payment_gateway_and_more'),
        ('services', '0008_clientservice_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('connection', 'Connection'), ('service', 'Service')], default='connection', help_text='What this payment is for.', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Set for service-listing contact-reveal payments.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='services.clientservice'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='connection',
            field=models.ForeignKey(blank=True, help_text='Set for hookup/connection payments.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='connections.connection'),
        ),
    ]
