# Generated by Django 6.0.6 on 2026-09-26 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_remove_connection_unique_active_connection_and_more'),
        ('payments', '0003_payment_payment_type_payment_service_and_more'),
        ('services', '0008_clientservice_is_featured_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='payment',
            name='category',
            field=models.CharField(choices=[('connection', 'Connection'), ('service', 'Service')], db_index=True, default='connection', help_text='What this payment is for.', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='connection',
            field=models.ForeignKey(blank=True, help_text='Set for connection payments (hookup or service contact reveal).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='connections.connection'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='payments_user_id_1b771c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['connection', 'status'], name='payments_connect_cf9ced_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['category', 'status'], name='payments_categor_d581a9_idx'),
        ),
    ]
