# Generated by Django 6.0.6 on 2026-09-26 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0005_remove_connection_unique_hookup_connection_and_more'),
        ('payments', '0004_remove_payment_payment_type_payment_category_and_more'),
        ('services', '0008_clientservice_is_featured_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_user_id_1b771c_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_connect_cf9ced_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_categor_d581a9_idx',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('connection', 'Connection'), ('service', 'Service')], default='connection', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='connections.connection'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('pesapal', 'PesaPal'), ('paystack', 'Paystack')], default='pesapal', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='services.clientservice'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='category',
        ),
    ]
