# Generated by Django 6.0.6 on 2026-09-26 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_payment_payments_user_id_1b771c_idx_and_more'),
        ('plans', '0002_remove_plan_posts_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Set for plan-subscription payments.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='plans.plan'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('connection', 'Connection'), ('service', 'Service'), ('plan', 'Plan Subscription')], default='connection', max_length=20),
        ),
    ]
