# Generated by Django 6.0.6 on 2026-09-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_plan_alter_payment_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='plan',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('connection', 'Connection'), ('service', 'Service')], default='connection', max_length=20),
        ),
    ]
