# Generated by Django 6.0.6 on 2026-10-04 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0006_remove_connection_connections_sender__6e3715_idx_and_more'),
        ('payments', '0007_remove_payment_plan_alter_payment_payment_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
