# Generated by Django 6.0.6 on 2026-10-10 08:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='active', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='When the subscription becomes effective.')),
                ('end_date', models.DateTimeField(blank=True, help_text='When it expires. Empty = never expires.', null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('payment_reference', models.CharField(blank=True, max_length=120, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='plans.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'status'], name='subscriptio_user_id_f643d5_idx'), models.Index(fields=['plan'], name='subscriptio_plan_id_01c978_idx'), models.Index(fields=['end_date'], name='subscriptio_end_dat_17ca3f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='one_active_subscription_per_user'), models.UniqueConstraint(condition=models.Q(('status', 'trialing')), fields=('user',), name='one_trialing_subscription_per_user')],
            },
        ),
    ]
