# Generated by Django 6.0.6 on 2026-09-26 17:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0002_remove_plan_posts_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When the subscription started (auto-set on create).')),
                ('end_date', models.DateTimeField(editable=False, help_text='When the subscription ends (auto-computed: start + 30 days).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.OneToOneField(help_text='The plan this subscription is on.', on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='plans.plan')),
                ('user', models.OneToOneField(help_text='The account this subscription belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions',
                'ordering': ['-start_date'],
            },
        ),
    ]
