# Generated by Django 6.0.6 on 2026-09-26 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_plan_alter_payment_payment_type'),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment',
            field=models.OneToOneField(blank=True, help_text='The payment that activates this subscription. Status is read from here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_subscription', to='payments.payment'),
        ),
    ]
