# Generated by Django 6.0.6 on 2026-09-26 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_plan_alter_payment_payment_type'),
        ('plans', '0002_remove_plan_posts_limit'),
        ('subscription', '0002_subscription_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(help_text='The plan this subscription is on. Many subscriptions can share the same plan.', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='plans.plan'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['plan', 'user'], name='subscriptio_plan_id_0eb08e_idx'),
        ),
    ]
