# Generated by Django 6.0.6 on 2026-09-27 10:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_remove_plan_posts_limit'),
        ('subscription', '0003_alter_subscription_plan_and_more'),
        ('subscription_payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment',
            field=models.OneToOneField(blank=True, help_text='The payment that activates this subscription. Status is read from here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_subscription', to='subscription_payment.subscriptionpayment'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='plans.plan'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
