# Generated by Django 6.0.6 on 2026-10-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_remove_subscription_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='End of the current subscription period. Leave blank to auto-compute: +30 days for paid plans, far-future for free plans. You can override this in the admin to test the active/expired behavior.', null=True),
        ),
    ]
