# Generated by Django 6.0.6 on 2026-10-01 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_alter_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Start of the current subscription period. Defaults to now on create; editable to allow backdating or testing.'),
        ),
    ]
