# Generated by Django 6.0.2 on 2026-03-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('nonbinary', 'Non-binary'), ('prefer_not_say', 'Prefer not to say')], max_length=20, null=True),
        ),
    ]
