# Generated by Django 6.0.2 on 2026-03-13 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_clientprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('role', 'admin')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='managed_by_superuser',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('role', 'superadmin')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_managed', to=settings.AUTH_USER_MODEL),
        ),
    ]
