# Generated by Django 6.0.6 on 2026-07-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_name', models.CharField(default='Pesapal', max_length=50)),
                ('ipn_id', models.CharField(help_text='Pesapal IPN ID returned after registering the IPN URL.', max_length=255, unique=True)),
                ('ipn_url', models.URLField(help_text='Registered IPN callback URL.', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Configuration',
                'verbose_name_plural': 'Payment Configurations',
                'db_table': 'payment_configurations',
            },
        ),
    ]
