# Generated by Django 6.0.6 on 2026-08-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentconfigurations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentconfiguration',
            name='callback_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='paymentconfiguration',
            name='public_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentconfiguration',
            name='secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentconfiguration',
            name='gateway_name',
            field=models.CharField(choices=[('pesapal', 'PesaPal'), ('paystack', 'Paystack')], default='pesapal', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentconfiguration',
            name='ipn_id',
            field=models.CharField(blank=True, help_text='Pesapal IPN ID returned after registering the IPN URL.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentconfiguration',
            name='ipn_url',
            field=models.URLField(blank=True, help_text='Registered IPN callback URL.', max_length=500, null=True),
        ),
    ]
