# Generated by Django 6.0.6 on 2026-07-18 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current available balance.', max_digits=12)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Funds pending clearance.', max_digits=12)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount earned by the user.', max_digits=12)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount withdrawn by the user.', max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Balance',
                'verbose_name_plural': 'User Balances',
            },
        ),
    ]
