# Generated by Django 6.0.6 on 2026-10-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='image_public_id',
        ),
        migrations.RemoveField(
            model_name='story',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.CharField(choices=[('journey', 'Journeys'), ('motivation', 'Motivation'), ('success', 'Success Stories'), ('experience', 'Experiences'), ('lessons', 'Lessons'), ('inspiration', 'Inspiration')], max_length=20),
        ),
    ]
