# Generated by Django 6.0.6 on 2026-10-04 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_remove_story_image_public_id_remove_story_image_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-created_at'], 'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['user'], name='stories_sto_user_id_9909a1_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['category'], name='stories_sto_categor_a6f1fa_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['created_at'], name='stories_sto_created_d8706d_idx'),
        ),
    ]
