# Generated by Django 6.0.6 on 2026-10-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_alter_story_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Total number of times this story was opened.'),
        ),
    ]
