# Generated by Django 6.0.6 on 2026-10-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_story_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='follows_count',
            field=models.PositiveIntegerField(default=0, help_text='Cached total number of follows.'),
        ),
        migrations.AddField(
            model_name='story',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, help_text='Cached total number of likes.'),
        ),
        migrations.AlterField(
            model_name='story',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
