# Generated by Django 6.0.6 on 2026-09-27 09:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0002_remove_plan_posts_limit'),
        ('subscription', '0003_alter_subscription_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_payment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('merchant_reference', models.CharField(max_length=100, unique=True)),
                ('order_tracking_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('gateway', models.CharField(choices=[('pesapal', 'PesaPal'), ('paystack', 'Paystack')], default='pesapal', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(help_text='The plan purchased in this payment.', on_delete=django.db.models.deletion.PROTECT, related_name='subscription_payments', to='plans.plan')),
                ('subscription', models.ForeignKey(help_text='The subscription this payment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscription.subscription')),
                ('user', models.ForeignKey(help_text='The user who paid.', on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription Payment',
                'verbose_name_plural': 'Subscription Payments',
                'db_table': 'subscription_payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subscription', 'status'], name='subscriptio_subscri_e7dc37_idx'), models.Index(fields=['user', 'status'], name='subscriptio_user_id_d0c042_idx'), models.Index(fields=['plan', 'status'], name='subscriptio_plan_id_9d5bcf_idx')],
            },
        ),
    ]
