# Generated by Django 6.0.6 on 2026-10-10 13:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        ('subscription', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_reference', models.CharField(db_index=True, help_text="Our unique reference for this payment. Sent to the gateway and returned on callbacks. Example: 'SUB-8-9F3A2C7D1B04'.", max_length=120, unique=True)),
                ('order_tracking_id', models.CharField(blank=True, db_index=True, help_text="The gateway's own identifier for this order. Populated after a successful SubmitOrderRequest.", max_length=120, null=True, unique=True)),
                ('gateway', models.CharField(choices=[('pesapal', 'PesaPal'), ('paystack', 'Paystack'), ('mpesa', 'M-Pesa')], default='pesapal', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed'), ('invalid', 'Invalid'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount charged, in the currency below.', max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=8)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('confirmation_code', models.CharField(blank=True, help_text='Gateway confirmation code / receipt number.', max_length=120, null=True)),
                ('payment_method', models.CharField(blank=True, help_text="e.g. 'card', 'mpesa', 'bank'.", max_length=80, null=True)),
                ('payment_account', models.CharField(blank=True, help_text='Masked account or phone the payment was charged to.', max_length=120, null=True)),
                ('submit_response', models.JSONField(blank=True, help_text='Full response from the initial order submission.', null=True)),
                ('status_response', models.JSONField(blank=True, help_text='Full response from the most recent status check.', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Populated when the payment fails or is reversed.', null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When the gateway confirmed the payment.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, help_text='The plan that was being purchased at the moment of checkout. SET_NULL preserves the record if the plan is later deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='plans.plan')),
                ('subscription', models.ForeignKey(blank=True, help_text='The subscription this payment belongs to. SET_NULL so payments survive subscription deletions as a financial audit trail.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscription.subscription')),
                ('user', models.ForeignKey(blank=True, help_text='The account that made the payment. Kept even if the subscription or plan are later removed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription Payment',
                'verbose_name_plural': 'Subscription Payments',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='subscriptio_status_b72e7d_idx'), models.Index(fields=['user', 'status'], name='subscriptio_user_id_b8dadd_idx'), models.Index(fields=['subscription', 'status'], name='subscriptio_subscri_4411cb_idx'), models.Index(fields=['plan', 'status'], name='subscriptio_plan_id_67eafc_idx'), models.Index(fields=['gateway', 'status'], name='subscriptio_gateway_087bd5_idx')],
            },
        ),
    ]
