# Generated by Django 6.0.6 on 2026-10-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_remove_subscription_payment_and_more'),
        ('subscription_payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subscriptionpayment',
            name='subscriptio_user_id_d0c042_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscriptionpayment',
            name='subscriptio_plan_id_9d5bcf_idx',
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount paid or expected for this payment.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='merchant_reference',
            field=models.CharField(help_text='Unique payment reference generated by Youpata.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='order_tracking_id',
            field=models.CharField(blank=True, help_text='Transaction tracking ID returned by the payment gateway, such as PesaPal.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Date and time the payment was confirmed.', null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='phone_number',
            field=models.CharField(help_text='Phone number used for the payment.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='subscriptionpayment',
            index=models.Index(fields=['order_tracking_id'], name='subscriptio_order_t_07d3ce_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionpayment',
            index=models.Index(fields=['gateway', 'status'], name='subscriptio_gateway_1e0f23_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionpayment',
            index=models.Index(fields=['created_at'], name='subscriptio_created_d843a2_idx'),
        ),
        migrations.RemoveField(
            model_name='subscriptionpayment',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscriptionpayment',
            name='user',
        ),
    ]
