# Generated by Django 6.0.6 on 2026-10-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_remove_subscription_payment_and_more'),
        ('subscription_payment', '0002_remove_subscriptionpayment_subscriptio_user_id_d0c042_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='confirmation_code',
            field=models.CharField(blank=True, help_text='Confirmation code returned by the payment provider (e.g. M-Pesa receipt number).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='currency',
            field=models.CharField(default='KES', help_text='ISO currency code.', max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='email',
            field=models.EmailField(blank=True, help_text='Email used during the payment.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message from the gateway or from our own processing, if any.', null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='payment_account',
            field=models.CharField(blank=True, help_text='Masked card number or phone number used during payment.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Payment method reported by the gateway (CARD, MPESA, MTN, TIGO, etc.).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='status_response',
            field=models.JSONField(blank=True, help_text='Raw response from GetTransactionStatus.', null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='submit_response',
            field=models.JSONField(blank=True, help_text='Raw response from SubmitOrderRequest.', null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='order_tracking_id',
            field=models.CharField(blank=True, db_index=True, help_text='Transaction tracking ID returned by the payment gateway, such as PesaPal.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number used for the payment.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed'), ('invalid', 'Invalid'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='subscriptionpayment',
            index=models.Index(fields=['merchant_reference'], name='subscriptio_merchan_fbc04e_idx'),
        ),
    ]
