# Generated by Django 6.0.6 on 2026-10-01 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_remove_plan_posts_limit'),
        ('subscription', '0005_remove_subscription_payment_and_more'),
        ('subscription_payment', '0003_subscriptionpayment_confirmation_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='The plan this payment is for.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='plans.plan'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message from the gateway or our processing.', null=True),
        ),
        migrations.AddIndex(
            model_name='subscriptionpayment',
            index=models.Index(fields=['plan', 'status'], name='subscriptio_plan_id_9d5bcf_idx'),
        ),
    ]
