# Generated by Django 6.0.6 on 2026-10-03 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0004_businesses_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('update', 'Update'), ('offer', 'Offer'), ('announcement', 'Announcement'), ('event', 'Event')], default='update', help_text='What kind of post this is.', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, help_text='Cloudinary image URL for this post.', max_length=1000, null=True)),
                ('image_public_id', models.CharField(blank=True, help_text='Cloudinary public ID — used for deletion / updates.', max_length=500, null=True)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin this post to the top of the business page.')),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('archived', 'Archived')], default='published', help_text='Publication state of the post.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, help_text='The user who created this post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_posts', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(help_text='The business this post belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='businesses.businesses')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ('-is_pinned', '-created_at'),
                'indexes': [models.Index(fields=['business'], name='posts_posts_busines_439a85_idx'), models.Index(fields=['business', 'status'], name='posts_posts_busines_fbd5f5_idx'), models.Index(fields=['post_type'], name='posts_posts_post_ty_c5e785_idx'), models.Index(fields=['created_at'], name='posts_posts_created_618100_idx')],
            },
        ),
    ]
