# Generated by Django 6.0.6 on 2026-10-03 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ('-created_at',), 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.RemoveIndex(
            model_name='posts',
            name='posts_posts_busines_fbd5f5_idx',
        ),
        migrations.RemoveIndex(
            model_name='posts',
            name='posts_posts_post_ty_c5e785_idx',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='body',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='author',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='is_pinned',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='post_type',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='status',
        ),
    ]
