# Generated by Django 6.0.6 on 2026-10-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_description_posts_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image_public_id',
            field=models.CharField(help_text='Cloudinary public ID — used for deletion / updates.', max_length=500),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image_url',
            field=models.URLField(help_text='Cloudinary image URL for this post.', max_length=1000),
        ),
    ]
