# Generated by Django 6.0.6 on 2026-10-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_posts_image_public_id_alter_posts_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Total number of times this post was opened.'),
        ),
    ]
