# Generated by Django 6.0.6 on 2026-06-27 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interested_in_gender', models.CharField(blank=True, choices=[('M', 'Men'), ('F', 'Women'), ('A', 'Everyone')], max_length=1, null=True)),
                ('minimum_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('maximum_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'user'}, on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preference',
                'verbose_name_plural': 'Preferences',
                'db_table': 'preferences',
                'ordering': ['-created_at'],
            },
        ),
    ]
