# Generated by Django 6.0.6 on 2026-07-15 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hookup_fee', models.DecimalField(decimal_places=2, default=100.0, help_text='Amount a user pays to obtain a connection.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(limit_choices_to={'role__in': ['admin', 'superadmin']}, on_delete=django.db.models.deletion.CASCADE, related_name='platform_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Configuration',
                'verbose_name_plural': 'Platform Configurations',
                'db_table': 'platform_configs',
            },
        ),
    ]
