# Generated by Django 6.0.6 on 2026-09-22 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platformconfig',
            old_name='hookup_fee',
            new_name='connection_fee',
        ),
        migrations.RemoveField(
            model_name='platformconfig',
            name='owner',
        ),
    ]
