# Generated by Django 6.0.6 on 2026-07-22 06:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=20.0, help_text='Commission percentage for the admin (0-100%). Example: 20 means admin gets 20%, platform gets 80%', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(help_text='Admin user this commission configuration belongs to', limit_choices_to={'role__in': ['admin', 'superadmin']}, on_delete=django.db.models.deletion.CASCADE, related_name='commission_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
                'db_table': 'commissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
