# Generated by Django 6.0.6 on 2026-09-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('services_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of services. Leave blank for unlimited.', null=True)),
                ('images_per_service', models.PositiveIntegerField(blank=True, help_text='Maximum images per service. Leave blank for unlimited.', null=True)),
                ('posts_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of posts. Leave blank for unlimited.', null=True)),
                ('stories_per_month', models.PositiveIntegerField(blank=True, help_text='Maximum stories per month. Leave blank for unlimited.', null=True)),
                ('profile_images_limit', models.PositiveIntegerField(default=1)),
                ('featured_listing', models.BooleanField(default=False)),
                ('verified_premium_badge', models.BooleanField(default=False)),
                ('priority_visibility', models.BooleanField(default=False)),
                ('analytics_level', models.CharField(choices=[('basic', 'Basic'), ('advanced', 'Advanced')], default='basic', max_length=20)),
                ('connection_fee_type', models.CharField(default='normal', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'price'],
            },
        ),
    ]
