# Generated by Django 6.0.6 on 2026-10-10 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(help_text="Display name, e.g. 'Starter', 'Pro', 'Business'.", max_length=80, unique=True)),
                ('slug', models.SlugField(help_text="URL-safe identifier, e.g. 'starter', 'pro'.", max_length=80, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Short marketing blurb shown under the plan name.')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Price in KES. Set to 0 for a free plan.', max_digits=10)),
                ('billing_cycle', models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='monthly', help_text="How often the price is charged. 'free' overrides price.", max_length=20)),
                ('businesses_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of businesses. NULL = unlimited.', null=True)),
                ('posts_limit', models.PositiveIntegerField(blank=True, help_text='Maximum posts per business. NULL = unlimited.', null=True)),
                ('products_limit', models.PositiveIntegerField(blank=True, help_text='Maximum products per business. NULL = unlimited.', null=True)),
                ('images_per_product', models.PositiveIntegerField(blank=True, help_text='Maximum images per product. NULL = unlimited.', null=True)),
                ('stories_per_month', models.PositiveIntegerField(blank=True, help_text='Maximum stories per month. NULL = unlimited.', null=True)),
                ('profile_images_limit', models.PositiveIntegerField(default=1, help_text='How many profile images the user may upload.')),
                ('featured_listing', models.BooleanField(default=False, help_text='Plan members appear in the featured section.')),
                ('verified_premium_badge', models.BooleanField(default=False, help_text='Plan members get the verified / premium badge.')),
                ('priority_visibility', models.BooleanField(default=False, help_text='Plan members rank higher in feeds and search.')),
                ('analytics_level', models.CharField(choices=[('none', 'None'), ('basic', 'Basic'), ('advanced', 'Advanced')], default='basic', max_length=20)),
                ('connection_fee_type', models.CharField(choices=[('normal', 'Normal'), ('reduced', 'Reduced'), ('waived', 'Waived')], default='normal', help_text='How the connection fee is charged for this plan.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text="Inactive plans don't appear anywhere.")),
                ('is_default', models.BooleanField(default=False, help_text='Mark this plan as the one assigned to new users. Only one plan may be the default at a time.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ('display_order', 'price', 'plan_name'),
                'indexes': [models.Index(fields=['is_active'], name='plans_plan_is_acti_50e816_idx'), models.Index(fields=['is_default'], name='plans_plan_is_defa_eaade9_idx'), models.Index(fields=['display_order'], name='plans_plan_display_675965_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='only_one_default_plan')],
            },
        ),
        migrations.CreateModel(
            name='PlanProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Property name, e.g. 'Support', 'Storage'.", max_length=120)),
                ('value', models.CharField(help_text="Property value, e.g. '24/7', '5 GB', 'Unlimited'.", max_length=500)),
                ('is_highlighted', models.BooleanField(default=False, help_text='Show this property with emphasis on the plan card.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order in which the property appears.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(help_text='The plan this property belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='plans.plan')),
            ],
            options={
                'verbose_name': 'Plan Property',
                'verbose_name_plural': 'Plan Properties',
                'ordering': ('sort_order', 'created_at'),
                'indexes': [models.Index(fields=['plan'], name='plans_planp_plan_id_187e41_idx')],
            },
        ),
    ]
