# Generated by Django 6.0.6 on 2026-09-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='posts_limit',
        ),
    ]
