# Generated by Django 6.0.6 on 2026-10-04 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientAssignment',
        ),
    ]
