# Generated by Django 6.0.6 on 2026-10-03 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0004_businesses_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price in KES. Optional.', max_digits=12, null=True)),
                ('image_url', models.URLField(help_text='Cloudinary image URL for this product.', max_length=1000)),
                ('image_public_id', models.CharField(help_text='Cloudinary public ID — used for deletion / updates.', max_length=500)),
                ('property1', models.CharField(blank=True, help_text='Optional property, e.g. Size: XL', max_length=200, null=True)),
                ('property2', models.CharField(blank=True, help_text='Optional property, e.g. Colour: Blue', max_length=200, null=True)),
                ('property3', models.CharField(blank=True, help_text='Optional property, e.g. Material: Cotton', max_length=200, null=True)),
                ('property4', models.CharField(blank=True, help_text='Optional property, e.g. Weight: 1.2kg', max_length=200, null=True)),
                ('property5', models.CharField(blank=True, help_text='Optional property, e.g. Warranty: 6 months', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(help_text='The business this product belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='businesses.businesses')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['business'], name='products_pr_busines_5b5815_idx'), models.Index(fields=['created_at'], name='products_pr_created_dc541f_idx')],
            },
        ),
    ]
