# Generated by Django 6.0.6 on 2026-10-09 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image_public_id',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='products',
            name='property1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='property2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='property3',
        ),
        migrations.RemoveField(
            model_name='products',
            name='property4',
        ),
        migrations.RemoveField(
            model_name='products',
            name='property5',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='Cloudinary image URL for this product image.', max_length=1000)),
                ('image_public_id', models.CharField(help_text='Cloudinary public ID — used for deletion / updates.', max_length=500)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark this image as the primary/cover image for the product.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order in which the image appears in the gallery.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='The product this image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.products')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ('sort_order', 'created_at'),
                'indexes': [models.Index(fields=['product'], name='products_pr_product_3d7874_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='unique_primary_image_per_product')],
            },
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Property name, e.g. 'Size', 'Colour', 'Material'.", max_length=200)),
                ('value', models.CharField(help_text="Property value, e.g. 'XL', 'Blue', 'Cotton'.", max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order in which the property appears.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='The product this property belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='property_items', to='products.products')),
            ],
            options={
                'verbose_name': 'Product Property',
                'verbose_name_plural': 'Product Properties',
                'ordering': ('sort_order', 'created_at'),
                'indexes': [models.Index(fields=['product'], name='products_pr_product_cc0243_idx')],
            },
        ),
    ]
