# Generated by Django 6.0.6 on 2026-10-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_products_image_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='follows_count',
            field=models.PositiveIntegerField(default=0, help_text='Cached total number of follows.'),
        ),
        migrations.AddField(
            model_name='products',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, help_text='Cached total number of likes.'),
        ),
    ]
