# subscription_payment/models.py
import uuid

from django.db import models

from subscription.models import Subscription


class SubscriptionPayment(models.Model):

    # ========================================================
    # STATUS
    # ========================================================

    STATUS_CHOICES = (
        ("pending", "Pending"),
        ("completed", "Completed"),
        ("failed", "Failed"),
        ("reversed", "Reversed"),
        ("invalid", "Invalid"),
        ("cancelled", "Cancelled"),
    )

    # ========================================================
    # GATEWAY
    # ========================================================

    GATEWAY_CHOICES = (
        ("pesapal", "PesaPal"),
        ("paystack", "Paystack"),
    )

    # ========================================================
    # IDENTIFIER
    # ========================================================

    subscription_payment_id = models.UUIDField(
        default=uuid.uuid4,
        editable=False,
        unique=True,
    )

    # ========================================================
    # RELATIONSHIPS
    # ========================================================

    subscription = models.ForeignKey(
        Subscription,
        on_delete=models.CASCADE,
        related_name="payments",
        help_text="The subscription this payment belongs to.",
    )

    plan = models.ForeignKey(
        "plans.Plan",
        on_delete=models.PROTECT,
        related_name="payments",
        null=True,
        blank=True,
        help_text="The plan this payment is for.",
    )

    # ========================================================
    # PAYMENT REFERENCES
    # ========================================================

    merchant_reference = models.CharField(
        max_length=100,
        unique=True,
        help_text="Unique payment reference generated by Youpata.",
    )

    order_tracking_id = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        db_index=True,
        help_text=(
            "Transaction tracking ID returned by the "
            "payment gateway, such as PesaPal."
        ),
    )

    confirmation_code = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        help_text=(
            "Confirmation code returned by the payment "
            "provider (e.g. M-Pesa receipt number)."
        ),
    )

    # ========================================================
    # PAYMENT DETAILS
    # ========================================================

    amount = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        help_text="Amount paid or expected for this payment.",
    )

    currency = models.CharField(
        max_length=10,
        default="KES",
        help_text="ISO currency code.",
    )

    phone_number = models.CharField(
        max_length=20,
        blank=True,
        null=True,
        help_text="Phone number used for the payment.",
    )

    email = models.EmailField(
        blank=True,
        null=True,
        help_text="Email used during the payment.",
    )

    payment_method = models.CharField(
        max_length=50,
        blank=True,
        null=True,
        help_text=(
            "Payment method reported by the gateway "
            "(CARD, MPESA, MTN, TIGO, etc.)."
        ),
    )

    payment_account = models.CharField(
        max_length=100,
        blank=True,
        null=True,
        help_text=(
            "Masked card number or phone number used "
            "during payment."
        ),
    )

    gateway = models.CharField(
        max_length=20,
        choices=GATEWAY_CHOICES,
        default="pesapal",
    )

    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default="pending",
        db_index=True,
    )

    # --------------------------------------------------------
    # RAW GATEWAY RESPONSES
    # --------------------------------------------------------

    submit_response = models.JSONField(
        blank=True,
        null=True,
        help_text="Raw response from SubmitOrderRequest.",
    )

    status_response = models.JSONField(
        blank=True,
        null=True,
        help_text="Raw response from GetTransactionStatus.",
    )

    # --------------------------------------------------------
    # ERROR
    # --------------------------------------------------------

    error_message = models.TextField(
        blank=True,
        null=True,
        help_text="Error message from the gateway or our processing.",
    )

    # ========================================================
    # DATES
    # ========================================================

    paid_at = models.DateTimeField(
        blank=True,
        null=True,
        help_text="Date and time the payment was confirmed.",
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    updated_at = models.DateTimeField(
        auto_now=True,
    )

    # ========================================================
    # META
    # ========================================================

    class Meta:
        db_table = "subscription_payments"

        ordering = ["-created_at"]

        verbose_name = "Subscription Payment"
        verbose_name_plural = "Subscription Payments"

        indexes = [
            models.Index(fields=["subscription", "status"]),
            models.Index(fields=["order_tracking_id"]),
            models.Index(fields=["gateway", "status"]),
            models.Index(fields=["created_at"]),
            models.Index(fields=["merchant_reference"]),
            models.Index(fields=["plan", "status"]),
        ]

    # ========================================================
    # STRING
    # ========================================================

    def __str__(self):
        plan_name = self.plan.name if self.plan else "—"
        return (
            f"{self.merchant_reference} — "
            f"{self.subscription.user.email} — "
            f"{plan_name} — "
            f"{self.status}"
        )

    # ========================================================
    # HELPERS
    # ========================================================

    @property
    def is_completed(self) -> bool:
        return self.status == "completed"

    @property
    def is_pending(self) -> bool:
        return self.status == "pending"

    @property
    def is_failed(self) -> bool:
        return self.status == "failed"

    @property
    def is_reversed(self) -> bool:
        return self.status == "reversed"

    @property
    def is_invalid(self) -> bool:
        return self.status == "invalid"

    @property
    def is_cancelled(self) -> bool:
        return self.status == "cancelled"

    @property
    def is_terminal(self) -> bool:
        return self.status in (
            "completed",
            "failed",
            "reversed",
            "invalid",
            "cancelled",
        )