# Generated by Django 6.0.6 on 2026-06-27 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, help_text="User's country of residence", max_length=100, null=True)),
                ('county', models.CharField(blank=True, help_text="User's county/state/province", max_length=100, null=True)),
                ('city', models.CharField(blank=True, help_text="User's city of residence", max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text="User's date of birth", null=True)),
                ('bio', models.TextField(blank=True, help_text="User's biography or description", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the profile was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the profile was last updated')),
                ('user', models.OneToOneField(help_text='The user this profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
