# Generated by Django 6.0.6 on 2026-10-04 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_remove_userprofile_id_alter_userprofile_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userprofile',
        ),
    ]
