# Generated by Django 6.0.6 on 2026-10-10 16:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current system balance amount.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_deposits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cumulative total of all deposits into the system.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_withdrawals', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cumulative total of all withdrawals from the system.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='KES', help_text='ISO currency code for the balance (e.g., KES, USD).', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System Balance',
                'verbose_name_plural': 'System Balance',
                'ordering': ['-updated_at'],
            },
        ),
    ]
